### ISSUE TITLE
chore: use the built-in `next/font` instead

### ISSUE THREAD

**Issue by priyankarpal** [sourceguidehq/main#4]
![image](https://github.com/sourceguidehq/main/assets/88102392/4f35fad2-37b9-40d2-ac87-8535897d4e56)

as you can see in the above image we're not using the built-in `next/font`. we've to fix this issue 

you can assign me

**Comment by ashura-code** [comment]
I have assigned you , you can fix the bug now

**Comment by priyankarpal** [comment]
completed
