### ISSUE TITLE
refactor: navbar.tsx

### ISSUE THREAD

**Issue by priyankarpal** [sourceguidehq/main#5]
We need to refactor the code in `navbar.tsx`. Currently, we are using a basic format that needs improvement. To enhance the code quality in the long run, we must create objects and use the `.map` method to fetch all navbar links. Additionally, we need to remove all unwanted code.

share your opinions too 

I can work on this issue. 

### file link 
https://github.com/sourceguidehq/main/blob/main/comps/navbar.tsx

**Comment by ashura-code** [comment]
Thank you for figuring the task in the navbar.tsx file. I appreciate the opportunity to enhance the code quality. Please go ahead with the change. Looking forward to improving the codebase!
