### ISSUE TITLE
Need appropriate margin for the programs page.

### ISSUE THREAD

**Issue by ashura-code** [sourceguidehq/main#7]
## The div containing the program cards in the desktop version of the app requires suitable left and right margins.

Main component link : https://github.com/sourceguidehq/main/blob/main/comps/Programs.tsx

Parent component link : https://github.com/sourceguidehq/main/blob/main/app/programs/page.tsx  

P.S : main component link is used in 44th line of parent component

<img width="1436" alt="Screenshot 2024-01-07 at 4 56 25 PM" src="https://github.com/sourceguidehq/main/assets/83760410/2eacb2e9-b49c-4351-ad51-760c1851e0e4">

**Comment by SamIsTheFBI** [comment]
Hey @ashura-code I'm willing to work on this issue. Can you assign this issue to me please?

**Comment by ezhillragesh** [comment]
Yeah sure you can start working on it @SamIsTheFBI
